version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: live-bidding-app-app:latest
    container_name: bidding-app-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
  mongo-data:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME={MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD={MONGO_DB_PASS}
      - MONGODB_URI={MONGODB_URI}
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:


